version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: burnoffadmin
      POSTGRES_PASSWORD: burnoffpass
      POSTGRES_DB: burnoffdb

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgressql/postgres_data

volumes: 
  postgres_data: