"""Mod Admin

Revision ID: 97378c0c1374
Revises: 2ef50a403b69
Create Date: 2025-06-23 22:47:29.840271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97378c0c1374'
down_revision = '2ef50a403b69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('super_admin', sa.Boolean(), nullable=True))
        batch_op.drop_column('can_create_admins')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_create_admins', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('super_admin')

    # ### end Alembic commands ###
