"""Mod Admin adding name and type

Revision ID: ea7cca7aeb1f
Revises: 6eca64228763
Create Date: 2025-06-24 22:30:20.931984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea7cca7aeb1f'
down_revision = '6eca64228763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('type', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('type')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
